[project]
name = "TipJarv1"
description = "Create a project from scratch: Start from a blank scaffold for your next Clarity contract"
authors = []
telemetry = true
cache_dir = "./.cache"

# [contracts.TipJarv1]
# path = "contracts/TipJarv1.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
